# .github/workflows/main.yml

name: Pipeline de Testes Python

# Gatilho: Executa em cada push para a branch main ou em Pull Requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona o repositório para o ambiente de execução
    - uses: actions/checkout@v3

    # 2. Configura o ambiente Python na versão 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # 3. Instala dependências (se houver)
    # Neste projeto simples, não há dependências externas
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    
    # 4. Executa os testes automatizados
    # O comando `python -m unittest discover` encontra e executa todos os testes na pasta 'tests'
    - name: Run tests
      run: |
        python -m unittest discover -s tests